#!/usr/bin/env python3
"""Emit Prism Character Mode roster bitmap tables.

Reads rosters_mapped.json (species already resolved to Prism internal ids by
map_species.py against prism_species_table.tsv) and writes:

  - rosters.asm       RGBDS include: one 32-byte bitmap per character
                       (256 bits, bit N = Prism species id N allowed;
                        LSB-first within each byte: bit = id & 7 of byte
                        id >> 3 — must match the catch-gate stub's check)
  - roster_index.tsv  character index -> name/category/source + species count
                       (the character id byte the gate reads is an index into
                        this order)

Characters are emitted in sorted(name) order, same as rosters_mapped.json's
key order. Empty rosters (Rijon Wiki documentation gaps, see CLAUDE.md) are
emitted as all-zero bitmaps and flagged in roster_index.tsv.

Evolution-family expansion is NOT applied yet (deferred until Prism's evo
data is reverse-engineered - matches map_species.py's note).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    with open(os.path.join(HERE, "rosters_mapped.json")) as f:
        mapped = json.load(f)

    names = sorted(mapped)
    bitmaps = []
    index_rows = []
    for idx, name in enumerate(names):
        info = mapped[name]
        ids = sorted({e["species_id"] for e in info["species"]
                      if e["species_id"] is not None})
        bm = bytearray(32)
        for sid in ids:
            if not 1 <= sid <= 255:
                raise SystemExit(f"{name}: species id {sid} out of range")
            bm[sid >> 3] |= 1 << (sid & 7)
        bitmaps.append(bytes(bm))
        flag = "EMPTY" if not ids else ""
        index_rows.append((idx, name, info["category"], info["source"],
                           len(ids), flag))

    with open(os.path.join(HERE, "rosters.asm"), "w") as f:
        f.write("; AUTO-GENERATED by emit_rosters.py - do not hand-edit.\n")
        f.write("; One 32-byte bitmap per character, bit N (LSB-first) = Prism\n")
        f.write("; species id N catchable. Character index order matches\n")
        f.write("; roster_index.tsv. See tools/character_mode/emit_rosters.py.\n")
        f.write(f"DEF NUM_CM_CHARACTERS EQU {len(names)}\n\n")
        f.write("CharacterModeRosters::\n")
        for (idx, name, cat, src, n, flag) in index_rows:
            f.write(f"; {idx:3d}: {name} ({cat}, {src}, {n} species{', EMPTY' if flag else ''})\n")
            bm = bitmaps[idx]
            for row in range(0, 32, 16):
                chunk = ", ".join(f"${b:02X}" for b in bm[row:row+16])
                f.write(f"\tdb {chunk}\n")
        f.write("CharacterModeRostersEnd::\n")

    with open(os.path.join(HERE, "roster_index.tsv"), "w") as f:
        f.write("index\tname\tcategory\tsource\tspecies_count\tflag\n")
        for row in index_rows:
            f.write("\t".join(str(x) for x in row) + "\n")

    n_empty = sum(1 for r in index_rows if r[5])
    print(f"emitted {len(names)} characters ({n_empty} empty rosters), "
          f"{len(names)*32} bytes of bitmap data")
    # quick self-check vs a known roster: Yuki should include Mamoswine 230
    yuki = names.index("Yuki") if "Yuki" in names else None
    if yuki is not None:
        bm = bitmaps[yuki]
        ok = bm[230 >> 3] & (1 << (230 & 7))
        print(f"self-check Yuki(idx {yuki}) has Mamoswine(230): {'OK' if ok else 'FAIL'}")


if __name__ == "__main__":
    main()
